name: Tests

on: [pull_request]

jobs:
  test-python:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [python-3.8, python-3.9, python-3.10, pypy-3.8]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Analysing the code with pylint
        continue-on-error: true
        run: |
          tox -e errors
      - name: Run pytests with coverage
        run: |
          tox -e test -- --junitxml=results.xml tests/
      - name: Convert coverage
        run: |
          tox -e coverage
