name: Tests

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.8, 3.9]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint mypy coverage pytest parameterized julia
      - name: Analysing the code with pylint
        run: |
          pylint `ls -R|grep .py$|xargs`
      - name: Analysing the code with pylint
        run: |
          pylint --exit-zero -disable=all --enable=similarities,unused-variable,unused-import,superfluous-parens src > pylint.json
      - name: Run pytests with coverage
        run: |
          coverage run --source=src -m pytest --junitxml=results.xml tests/
      - name: Convert coverage
        run: |
          coverage xml
          coverage report
